version: "3"

services:
    ckan-web:
        environment:
            - CKAN_SITE_URL=http://ckan-web:5000 # Setup redirects to work inside docker-compose
    cypress:
        image: cypress/included:7.3.0
        entrypoint: []
        command: /bin/bash -c 'npx wait-on http://ckan-web:5000 && cypress run'
        working_dir: /e2e
        depends_on:
        - ckan-web
        - ckan-worker
        volumes:
        - ./e2e:/e2e
