  
version: "3"

services:
  ckan-web:
    build:
      context: ckan/
      args:
        REQUIREMENTS_FILE: requirements.txt
        CKAN_ENV: development
    command: "/srv/app/start_ckan_web_dev.sh"
    env_file:
      - .env
    depends_on:
      - db
      - solr
      - redis
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
    volumes:
      - ./src:/srv/app/src_extensions
      - ckan_storage:/var/lib/ckan
      - ./requirements:/requirements

  ckan-worker:
    build:
      context: ckan/
    command: "/srv/app/start_ckan_worker.sh paster --plugin=ckan search-index rebuild -c /srv/app/production.ini"
    env_file:
      - .env
    depends_on:
      - db
      - solr
      - redis
      - ckan-web

  db:
    env_file:
      - .env
    build:
      context: postgresql/
    volumes:
      - pg_data:/var/lib/postgresql/data

  solr:
    build:
      context: solr/
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data/index

  redis:
    image: redis:alpine

volumes:
  ckan_storage:
  pg_data:
  solr_data: