  
version: "3"

services:
  ckan-web:
    # image: doi-ckan:latest
    image: doi-ckan:dev
    # command: "/srv/app/start_ckan_web.sh"
    command: "/srv/app/start_ckan_web_dev.sh"
    env_file:
      - .env
    depends_on:
      - db
      - solr
      - redis
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
    volumes:
      - ./src:/srv/app/src_extensions
      - ckan_storage:/var/lib/ckan
      - ./requirements:/requirements

  ckan-worker:
    image: doi-ckan:latest
    # image: doi-ckan:dev
    command: "/srv/app/start_ckan_worker.sh wait_for_init ckan-web 5000"
    env_file:
      - .env
    depends_on:
      - db
      - solr
      - redis
      - ckan-web
    volumes:
      - ./src:/srv/app/src_extensions

  db:
    env_file:
      - .env
    build:
      context: postgresql/
    volumes:
      - pg_data:/var/lib/postgresql/data

  solr:
    build:
      context: solr/
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data

  redis:
    image: redis:alpine

volumes:
  ckan_storage:
  pg_data:
  solr_data: