  
version: "3"

services:
  ckan-web:
    image: doi-ckan:latest
    # image: doi-ckan:dev
    command: "/srv/app/start_ckan_web.sh"
    # command: "/srv/app/start_ckan_web_dev.sh"
    env_file:
      - .env
    depends_on:
      - db
      - solr
      - redis
    ports:
      # nginx endpoint
      - "0.0.0.0:${CKAN_PORT}:5000"
      # wsgi server endpoint
      - "0.0.0.0:5001:5001"
    volumes:
      - ./ckan/requirements.txt:/srv/app/requirements.txt
      - ./ckan/requirements.in.txt:/srv/app/requirements.in.txt
      - ./ckan/requirements.sh:/srv/app/requirements.sh
      - ./src:/srv/app/src_extensions
      - ckan_storage:/var/lib/ckan
      - ./ckan/nginx_ckan:/etc/nginx/nginx.conf

  ckan-worker:
    image: doi-ckan:latest
    # image: doi-ckan:dev
    command: "/srv/app/start_ckan_worker.sh wait_for_init ckan-web 5000"
    env_file:
      - .env
    depends_on:
      - db
      - solr
      - redis
      - ckan-web
      - nginx-harvest-source
    volumes:
      - ./src:/srv/app/src_extensions

  db:
    env_file:
      - .env
    build:
      context: postgresql/
    volumes:
      - pg_data:/var/lib/postgresql/data

  solr:
    build:
      context: solr/
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data

  redis:
    image: redis:alpine

  nginx-harvest-source:
    image: nginx
    volumes:
      - ./harvest_test/harvest-sources:/usr/share/nginx/html
      - ./harvest_test/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  ckan_storage:
  pg_data:
  solr_data:
